name: "DWG to PDF Converter"
version: "1.0.0"
slug: "dwg2pdf_converter"
description: "Web-App zur Vorschau von DWG-Pl√§nen, Ebenen-Steuerung und PDF-Export."
url: "https://github.com/IHR-GITHUB-NAME/ha-addon-dwg2pdf"
arch:
  - amd64
  - aarch64
boot: auto
ingress: true
ingress_port: 8062
ports:
  8062/tcp: 8062
webui: "http://[HOST]:[PORT:8062]"
